//------------------------------------------------------------------------
// Copyright(c) 2023 OpenVpi Team.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Diffscope VSTi.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Diffscope VSTi VST3 (64Bit)"
#else
#define stringFileDescription	"Diffscope VSTi VST3"
#endif
#define stringCompanyName		"OpenVpi Team\0"
#define stringLegalCopyright	"Copyright(c) 2023 OpenVpi Team."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
